### PR TITLE
Added CONTRIBUTING.md

### LINKED ISSUE #7: Want to add Contributor's Guideline
This will work as a guide for open source beginners to contribute.
I want to work on this issue under DCP'21, please assign me this @Jagannath8

### PR DESCRIPTION
**Pull request by aakankshabhende**
Closes: #7

### CODE REVIEW

**Review by Jagannath8 — APPROVED** [review]

**Comment by Jagannath8** [comment]
@aakankshabhende You all have to fill this form after your pull request get merged. This will be used to calculate points.
Link: https://docs.google.com/forms/d/e/1FAIpQLSeHqAaYHdWPfzRdkdmEwCmM7YK6VLl-otseD0fQr3rFDget5w/viewform

Fill this for previous PR too

**Comment by Jagannath8** [comment]
Hey @aakankshabhende, in github ID you have to provide github profile name

**Comment by aakankshabhende** [comment]
Sorry sir, I filled github ID @Jagannath8

**Comment by Jagannath8** [comment]
> Sorry sir, I filled github ID @Jagannath8

No problem @aakankshabhende , just edit and make the changes

**Pull request merged**
