### PR TITLE
Create Design Report an Issue page

### PR DESCRIPTION
**Pull request by comnk**
Includes the page with working functionality of sending html responses to email

Need to create a temp gmail email and password in order to protect information, and also run Flask on 
the IP address of 127.0.0.1 in order to work correctly

Will update if anything else is needed

### CODE REVIEW

**Comment by Jagannath8** [comment]
@comnk 
When we send some issue it shows internal server error
Check once!
image

**Comment by comnk** [comment]
did you insert  into the required fields in the flask program?

**Comment by comnk** [comment]
the os.environ.get lines in app.py

**Comment by comnk** [comment]
it actually has to be a real gmail account with password

**Comment by comnk** [comment]
ps less secure apps setting on gmail has to be on

**Comment by comnk** [comment]
are you fine with using gmail api (includes getting gcp free tier)?

**Comment by comnk** [comment]
or other api instead of smtp

**Comment by Jagannath8** [comment]
> are you fine with using gmail api (includes getting gcp free tier)?

Okay @comnk 
Try for it

**Comment by comnk** [comment]
can I just submit the html and the css only for now?

**Comment by comnk** [comment]
i'll need to create a virtual environment to install the Gmail API library

**Review by Jagannath8 — CHANGES_REQUESTED** [review]
image
@comnk Everything is fine, just add those social media links

**Comment by comnk** [comment]
Do you have 2 factor authentication on for your gmail? You can create an app password for the Flask script

**Comment by comnk** [comment]
so I can remove my email and password

**Comment by comnk** [comment]
https://towardsdatascience.com/automate-sending-emails-with-gmail-in-python-449cc0c3c317

**Comment by comnk** [comment]
as reference, but only two factor part because python examples are outdated

**Review by Jagannath8 — APPROVED** [review]
Good work @comnk

**Comment by Jagannath8** [comment]
@comnk Do fill this form
https://docs.google.com/forms/d/e/1FAIpQLSeHqAaYHdWPfzRdkdmEwCmM7YK6VLl-otseD0fQr3rFDget5w/viewform?usp=sf_link

**Pull request merged**
